#!/bin/bash

apt-get update

apt-get -y install linux-tools-common \
    task-spooler \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

apt-get update
apt-get install docker-ce docker-ce-cli containerd.io

# Install docker-compose https://github.com/docker/compose/releases
curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Disable intel_pstate which remove Intel turbo boost
# http://www.webupd8.org/2014/04/prevent-your-laptop-from-overheating.html
# Good to read: https://bbs.archlinux.org/viewtopic.php?pid=1294415
sed -i 's/intel_pstate=enable/intel_pstate=disable/' /etc/default/grub
update-grub
